### ISSUE TITLE
Background only with no interface.

### ISSUE THREAD

**Issue by jonnyhoff** [astrofox-io/astrofox#10]
![image](https://user-images.githubusercontent.com/8642945/95630343-f9075b80-0a81-11eb-92e7-448ca1a77c4e.png)

**Comment by chr-ge** [comment]
Did you download the executable from [astrofox.io](https://astrofox.io/) or did you clone the source code and run it?

**Comment by mikecao** [comment]
You can't run it in your browser. You need to run Electron to start the app.

**Comment by jonnyhoff** [comment]
I've tried the appimage which did not work (Not compatible with Fedora linux) then sourcecode which resulted in the submitted issue.

Did run the Electron app and ffmpeg is in the bin folder as per steps.

both `yarn start` and `yarn dev` has the same output.

**Comment by jakiestfu** [comment]
@jonnyhoff Run `yarn dev` first, and then in a second terminal session, run `yarn start`. You must wait for the `yarn dev` task to finish before content will render in the electron app.
