### ISSUE TITLE
Effects reacts to audio?

### ISSUE THREAD

**Issue by kommit** [astrofox-io/astrofox#14]
I think it will be more useful if we could modulate effects with audio.

**Comment by mikecao** [comment]
You can using reactors. Click the little lightning bolt icon.

![image](https://user-images.githubusercontent.com/477975/95644703-45946c00-0a6d-11eb-8e07-3914b142486b.png)

I really need to work on the documentation 😓.

**Comment by kommit** [comment]
Thanks @mikecao, this is exactly what I want. Really cool!

I just watched the intro video again. This feature is shown in the video. I didn't notice that. Sorry for my stupid question.
