### ISSUE TITLE
Support for the OPUS audio codec

### ISSUE THREAD

**Issue by benthillerkus** [astrofox-io/astrofox#18]
The format YouTube uses for the audio only streams is *OPUS* inside of a *.webm* container (try `youtube-dl -F {some url}`). When downloaded, those files can be played in Chrome by just dragging them onto the tab bar; they are natively supported.

BTW, thanks for your work, it really means alot!

**Comment by mikecao** [comment]
It looks like Chrome can support it, https://caniuse.com/opus, so I just need to enable it.

**Comment by mikecao** [comment]
Fixed in 6a364ab302495a3356a308cb916196f91f3c6ae7
