### ISSUE TITLE
Video export not working

### ISSUE THREAD

**Issue by benthillerkus** [astrofox-io/astrofox#19]
### Description
Whenever I try to export a video, it'll open the video rendering view, show some random number for the elapsed time and claim that it's finished. It doesn't export a video though.

*I'm using the v0.1.6 AppImage*

![image](https://user-images.githubusercontent.com/29630575/95774738-43c2e680-0cc1-11eb-852d-539f8a38635c.png)

### System Configuration
|Computer||
|:----|----|
|Processor | Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz |
|Memory | 8039MB (2437MB used) |
|Device-Type | Notebook |
|OS | Manjaro Linux |

|Display||
|:----|----|
|Resolution | 1920x1080 pixels |
|Session Display Server | The X.Org Foundation 1.20.9 |

|Audio-Devices||
|:----|----|
|Audio Adapter | HDA-Intel - HDA Intel PCH |

**Comment by mikecao** [comment]
It seems the issue is the AppImage can't find the bundled ffmpeg. I'll see what I can find.

**Comment by benthillerkus** [comment]
It's working now in v0.1.7.
