### ISSUE TITLE
Don't use PNGs for rendering

### ISSUE THREAD

**Issue by benthillerkus** [astrofox-io/astrofox#21]
So, as far as I can see, when rendering an animation, Astrofox first exports a *.png* sequence and then calls *ffmpeg* to render the images into a video file.

I'd really recommend to not use PNGs for that, because:
- Encoding and Decoding PNGs is pretty slow
- PNGs are unreasonably large for everything that isn't flat colors
- PNGs have broken color management

As alternatives I'd suggest EXR if the goal is to be lossless (I guess TARGA / *.tga* would be fine too) or just plain old JPEGs.

Here are some references / benchmarks:
https://blender.stackexchange.com/a/148466
https://medium.com/@aeriform.io/what-i-learnt-about-png-files-the-hard-way-f39c69e897ce
https://youtu.be/F1kYBnY6mwg
https://twitter.com/troy_s/status/1157434283776040960

**Comment by mikecao** [comment]
It actually doesn't generate a sequence of files. It calls ffmpeg first, then renders frame by frame and passes it directly to ffmpeg. The method to extract the frame is https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL. I don't think EXR is supported. I can experiment with other supported formats to see if there's a difference, but my guess is that it's likely negligible vs the actual encoding time. I appreciate the info though.
