### ISSUE TITLE
Save canvas size in project file

### ISSUE THREAD

**Issue by verekia** [astrofox-io/astrofox#25]
Unless I'm doing something wrong, it seems that loading up a project doesn't set the canvas at the size of when that project was saved. It would be nice if it did :)

**Comment by mikecao** [comment]
This is probably a bug. It should already do that. I will take a look.

**Comment by ryhankabir562** [comment]
Hey would you help me how can i install it on Kali Linux

**Comment by ryhankabir562** [comment]
> This is probably a bug. It should already do that. I will take a look.
Hey would you help me how can i install it on Kali Linux

**Comment by mikecao** [comment]
This should be fixed now.

**Comment by ryhankabir562** [comment]
Will it work now?
