### ISSUE TITLE
Can't launch since "Updated Electron and other packages." + How to debug in vscode?

### ISSUE THREAD

**Issue by DerekZiemba** [astrofox-io/astrofox#26]
I saved this repo after seeing it on reddit to use as an example of how to structure, setup, create, build, and package an electron app.  This repo appears to be well organized and tries to work with the latest Electron, React, and Redux versions.  
* I see you switched to Zustand.  I imagine you couldn't get Redux to work with Electron 9+? I couldn't either and it's a reason why I was trying to find apps on github using newer electron to use as examples.  I'll have to check Zustand out. 

However, since your upgrade from electron 8 to 10, I haven't been able to get this repo to work. 

## Can't launch since "Updated Electron and other packages."
Astrofox was working until ***Updated Electron and other packages.*** https://github.com/astrofox-io/astrofox/commit/52ccc58261db14eb47d175a351d627839ced32a5
Then from that commit up to but not including _***Merge branch 'master' of https://github.com/chr-ge/astrofox***_ https://github.com/astrofox-io/astrofox/commit/601a32108182c8ad6cb8eebcdc306598420696e5 I'm met with:
```
(node:17332) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir 'C:\Users\Derek\AppData\Local\Google\Chrome\User Data\Default\Extensions\fmkadmapgofadopljbjfkapdkoienihi'
    at Object.readdirSync (fs.js:876:3)
    at Object.fs.readdirSync (electron/js2c/asar.js:621:39)
    at loadExtensions (A:\Code\github\astrofox-io\astrofox\app\main.js:31400:8)
    at init (A:\Code\github\astrofox-io\astrofox\app\main.js:31420:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async App.<anonymous> (A:\Code\github\astrofox-io\astrofox\app\main.js:31309:3)
```

After which from _***Merge branch 'master' of https://github.com/chr-ge/astrofox***_ https://github.com/astrofox-io/astrofox/commit/601a32108182c8ad6cb8eebcdc306598420696e5 to current master ***Merge pull request #24 from chr-ge/master*** https://github.com/astrofox-io/astrofox/commit/180809f59a6eb63ea1d6182ce90c4fba5e51b463 I'm met with:

![image](https://user-images.githubusercontent.com/7283693/97355048-58c47b80-1864-11eb-9094-5f9ac78c7866.png)

## How to Debug this app in VSCode?
I can't figure out the proper launch.config to debug this app and see your `.gitignore` excludes `.vscode`.  
Can you please remove that entry or add exceptions `!.vscode/launch.json` and  `!.vscode/tasks.json`?
So far I have the following in launch.config but it's not working: 
```js
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Electron: DevServer",
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceFolder}",
      "preLaunchTask": "yarn build-electron",
      "runtimeExecutable": "yarn",
      "runtimeArgs": [ "run", "dev-view" ],
    },
    {
      "name": "Electron: Main",
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceFolder}",
      "protocol": "inspector",
      // Doesn't work
      "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/dotenv",
      "runtimeArgs": [ "electron", "./app" ],
      // Can't set breakpoints
      "runtimeExecutable": "yarn",
      "runtimeArgs": [ "start", ],
    },
    { // Fails to attach to the renderer
      "name": "Electron: Renderer",
      "type": "chrome",
      "request": "attach",
      "port": 9223,
      "webRoot": "${workspaceFolder}",
      "timeout": 30000
    }
  ],
  "compounds": [
    {
      "name": "Electron: All",
      "configurations": [
        "Electron: DevServer",
        "Electron: Main",
        "Electron: Renderer",
      ]
    }
  ]
}
```

**Comment by mikecao** [comment]
Sorry, I was in the middle of changes to support plugins. It should work if you create a `plugins` directory at the root. If not you can pull this version d7c5e2f8f7f38e7b3241d01fce39b8c5394e5956 which is what is currently released.

As for Zustand, I switched to it because it is much easier to work with than Redux. It simplified a lot of the code and provided the same functionality.

The `.gitignore` for `.vscode` is just to not check in files into the repo. They should still work if they exist on your system.
