### ISSUE TITLE
Video export is slow - Very small use of processor/ram/etc...

### ISSUE THREAD

**Issue by Diissolution** [astrofox-io/astrofox#38]
When redering a video, Astrofox only uses a small amount of the ressources of my computer. 
Here is a screenshot of the ressource consumption during a rendering in 1920*1080, 60 fps "Medium" quality.

![image](https://user-images.githubusercontent.com/18014766/110249790-2ba57980-7f78-11eb-95cc-98626367b138.png)

**Comment by ctournayre** [comment]
+1 here with same settings, realtime render is ok, but export is very slow.

**Comment by mikecao** [comment]
The export is slow because it uses ffmpeg to create the video. It's encoding frame by frame. You should see an ffmpeg.exe process using a lot of CPU.

**Comment by Diissolution** [comment]
> The export is slow because it uses ffmpeg to create the video. It's encoding frame by frame. You should see an ffmpeg.exe process using a lot of CPU.

Oh I see, I did not think of that sorry ^^
thanks !
