### ISSUE TITLE
Sound Wave rendering issue

### ISSUE THREAD

**Issue by KatamariJr** [astrofox-io/astrofox#41]
Hello, loving Astrofox! I am using 1.2.0 currently on Windows 10 and experiencing this issue with the Sound Wave object, but only on render.

![gif of problem](https://user-images.githubusercontent.com/4542759/116795032-eb5a0780-aa9f-11eb-8d23-cf48056dbe2d.gif)

**Comment by mikecao** [comment]
Yes, this is a know issue and I'm working on a fix.

**Comment by mikecao** [comment]
This should be fixed now in v1.3.0.
