### ISSUE TITLE
too slow rendering

### ISSUE THREAD

**Issue by ChetanAmrao** [astrofox-io/astrofox#43]
Recently, I managed to edit a 2 hour audio clip of a podcast and was happy it was done after 2 weeks (phew!) but when I loaded the audio on the Stage it took some time to import. I edit a sample before and just hit render on the same project. It took me 6 hours to render it on lower preset at 30fps for 480p resolution.

I don't know what is the issue.

I thought about some solutions.
 1. use the GPU with [this](https://gpu.rocks/)
 2. optimize using some tips from [here](https://attackingpixels.com/tips-tricks-optimizing-three-js-performance/)
 3. Nvidia hardware specific  using something from [here](https://docs.nvidia.com/video-technologies/video-codec-sdk/ffmpeg-with-nvidia-gpu/)

I am not great at JS but had some time to think on this, would like this project to improve😀

**Comment by MikeFoden** [comment]
@ChetanAmrao 6 hours to render a 2 hour video shouldn't be too bad I would think.

**Comment by deathowl** [comment]
I'm also affected. 1,5 hours of render time for a 5 min video with 4 scenes. It's a Ryzen 5 system. I think adding GPU acceleration would be a huge gain indeed. I might try to swing my axe on it during the coming weekend, because otherwise i like astrofox a lot

**Comment by ChetanAmrao** [comment]
> @ChetanAmrao 6 hours to render a 2 hour video shouldn't be too bad I would think.

yes, its not but it was just an image most of the clip with a Wave animation for voice, I want to think of contributing in a good way to this project.

**Comment by ChetanAmrao** [comment]
> I'm also affected. 1,5 hours of render time for a 5 min video with 4 scenes. It's a Ryzen 5 system. I think adding GPU acceleration would be a huge gain indeed. I might try to swing my axe on it during the coming weekend, because otherwise i like astrofox a lot
