### ISSUE TITLE
Time Remaining UI during Render

### ISSUE THREAD

**Issue by jakiestfu** [astrofox-io/astrofox#5]
Would love to contribute to this project. I would love to see a "time remaining" feature during rendering. Is this something you'd be interested in? If so, do you care if I add dependencies or would you prefer to write the time remaining logic directly in the source?

Thanks for the awesome project!

---

Edit: As a followup, it might be nice to have some rules of conduct for PR solicitation, would love to just write this PR knowing you're open to it!

**Comment by mikecao** [comment]
Yes, I need to work on a `CONTRIBUTING.md`. But I am open to small PRs preferably and to not import any modules unless absolutely needed.

**Comment by jakiestfu** [comment]
https://github.com/astrofox-io/astrofox/pull/7
