### ISSUE TITLE
render error: Fedora user, had to chmod +x astrofox/bin/ffmpeg

### ISSUE THREAD

**Issue by catpea** [astrofox-io/astrofox#59]
When generating the video the program would report error
I went to the electron console it said EACCESS /home/catpiss/astrofox/bin/ffmpeg
I ran chmod +x /home/catpiss/astrofox/bin/ffmpeg
and that fixed the issue for me

uname -a
Linux black 5.14.11-200.fc34.x86_64 #1 SMP Sun Oct 10 14:39:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mikecao** [comment]
I'll probably have to add a chmod to the install script.
