### ISSUE TITLE
FLAC file support?

### ISSUE THREAD

**Issue by kennedy** [astrofox-io/astrofox#6]
Hello,
The app only allows these extentions. 

https://github.com/astrofox-io/astrofox/blob/a769113e119931e85068607cf596300cdbb81fd9/src/view/actions/audio.js#L75

I traced the [loadAudioData](https://github.com/astrofox-io/astrofox/blob/a769113e119931e85068607cf596300cdbb81fd9/src/utils/audio.js#L4) function down to where it loads the [AudioBuffer](https://github.com/astrofox-io/astrofox/blob/a769113e119931e85068607cf596300cdbb81fd9/src/audio/Audio.js#L14), however I couldnt find the source code for the buffer class. 

Is the audio engine is able to handle FLAC files?

**Comment by mikecao** [comment]
Depends on whether Chrome can handle it. Looks like it can, https://caniuse.com/flac

**Comment by mikecao** [comment]
Fixed in 1edfecc1a3c4586e0ba8ad7655eafa2eef6ce46a
