### ISSUE TITLE
Over 90% of CPU Memory usage when rendering a video

### ISSUE THREAD

**Issue by Mastartiq** [astrofox-io/astrofox#63]
Astrofox uses a huge amount of CPU, over 90% when rendering a video from it, even on medium quality and less than 30fps. The particular process that I saw to eat that much CPU is the ffmpeg one.

**Comment by mikecao** [comment]
This is normal. Video rendering is an intensive process. If you've ever used Handbrake or After Effects you would be similar CPU usage.

**Comment by jaygarcia** [comment]
Thanks @Mastartiq . Might make sense to close this issue as it's not actionable, i suppose?
